repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=79]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args:
          - --ignore-missing-imports
          - --show-error-codes

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks

  - repo: https://github.com/myint/rstcheck
    rev: v3.4.0
    hooks:
      - id: rstcheck
        additional_dependencies: [rstcheck]
        # resolutions here seem to indicate ignoring this message is easiest
        args: [--ignore-messages=(.*No directive entry for \"autofunction\".*)]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
      - id: setup-cfg-fmt
