sudo: false

language:
  - python

python:
  - 2.7
  - 3.6
  - 3.9

install:
  - pip install -r requirements.txt

script:
  - pycodestyle somepackage
  - pytest --verbose --capture=no datetime_formate
  - pip install .

notifications:
  email: false
